// Project Mordecai — Native Gameplay Tag Declarations (US-002)

#pragma once

#include "NativeGameplayTags.h"

namespace MordecaiGameplayTags
{
	// State tags (US-003)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Airborne);

	// State tags (US-004)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ComboWindow);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Rooted);

	// State tags (US-005)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dodging);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_PerfectDodge);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DodgeCooldown);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_PostureBroken);

	// State tags (US-006)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Blocking);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_PerfectBlock);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_GuardBroken);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Parrying);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Parried);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Riposte);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ParryWhiff);

	// State tags (US-007)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_KnockedDown);

	// Stamina tier tags (US-008)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina_Tier_Green);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina_Tier_Yellow);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina_Tier_Red);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina_Tier_Exhausted);

	// State tags (US-008)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Sprinting);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_StaminaRegenPaused);

	// Status effect tags (US-007 stubs)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Weakened);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Brittle);

	// Event tags (US-006)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ParryInput);

	// Event tags (US-011)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_SkillMilestone);

	// SetByCaller data tags (US-004)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_HealthDamage);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_PostureDamage);

	// SetByCaller data tags (US-008)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_StaminaCost);

	// Team tags (US-009)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Enemy);

	// Damage type tags (AC-002.11)
	// Physical subtypes are nested under Physical per damage_types_v1.md
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical_Slash);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical_Pierce);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical_Blunt);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Fire);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Frost);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Lightning);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Poison);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Corrosive);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Arcane);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Shadow);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Radiant);
}
