// Project Mordecai — Native Gameplay Tag Declarations (US-002)

#pragma once

#include "NativeGameplayTags.h"

namespace MordecaiGameplayTags
{
	// State tags (US-003)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Airborne);

	// State tags (US-004)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ComboWindow);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Rooted);

	// State tags (US-005)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dodging);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_PerfectDodge);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DodgeCooldown);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_PostureBroken);

	// State tags (US-006)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Blocking);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_PerfectBlock);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_GuardBroken);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Parrying);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Parried);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Riposte);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ParryWhiff);

	// State tags (US-007)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_KnockedDown);

	// Stamina tier tags (US-008)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina_Tier_Green);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina_Tier_Yellow);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina_Tier_Red);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina_Tier_Exhausted);

	// State tags (US-008)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Sprinting);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_StaminaRegenPaused);

	// Status effect tags (US-013)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Burning);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Bleeding);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Poisoned);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Frostbitten);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Shocked);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Weakened);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Brittle);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Silenced);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Rooted);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Blinded);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Fear);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Cursed);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Exposed);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Corroded);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Drenched);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Focused);

	// Status effect category tags (US-013)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Category_DoT);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Category_Debuff);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Category_Control);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Category_Buff);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Category_Environmental);

	// Immunity tags (US-013)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Burning);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Bleeding);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Poisoned);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Frostbitten);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Shocked);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Weakened);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Brittle);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Silenced);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Rooted);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Blinded);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Fear);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Cursed);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Exposed);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Corroded);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Drenched);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immunity_Focused);

	// State tags (US-014)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Casting);

	// Event tags (US-006)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ParryInput);

	// Event tags (US-011)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_SkillMilestone);

	// Event tags (US-012)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_FeatUnlocked);

	// Event tags (US-014)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_CastInterrupted);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_DamageTaken);

	// SetByCaller data tags (US-004)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_HealthDamage);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_PostureDamage);

	// SetByCaller data tags (US-008)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_StaminaCost);

	// Team tags (US-009)
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Enemy);

	// Damage type tags (AC-002.11)
	// Physical subtypes are nested under Physical per damage_types_v1.md
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical_Slash);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical_Pierce);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical_Blunt);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Fire);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Frost);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Lightning);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Poison);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Corrosive);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Arcane);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Shadow);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Radiant);
}
